### ISSUE TITLE
Way to set custom line?

### ISSUE THREAD

**Issue by richardpl** [amiaopensource/sccyou#8]
Because sometimes, source is previously scaled or filtered so line get leaked to other nearby lines.
Also detection heuristic could calculate and pick line with most detected captions.

**Comment by dericed** [comment]
I think that scaling may be what happened at https://twitter.com/bturkus/status/1197564971397402624/photo/3 and the actual captioned line is the next one.

The line is detected at https://github.com/amiaopensource/sccyou/blob/2148c95b3c725f2a4af338fcae2c7268d61569fe/sccyou#L76 where the values of `lavfi.readeia608.0.line` are tallied and the most popular one is used. However this process gets the most commonly occurring first line, rather than the line that most resembles captions, so traces of scaling can be misidentified as the captions in this case.
